### ISSUE TITLE
Use Internal Flash for DFU

### ISSUE THREAD

**Issue by AliMoal** [lulf/watchful#6]
Hi, thank you for your useful repo.
I need to use internal flash for DFU partition.
I used `nrf_softdevice::Flash` for it but it says the trait `NorFlash` is not implemented for this.
What should I do that?
Thanks again.

**Comment by lulf** [comment]
See https://github.com/embassy-rs/embassy/issues/2679 . Look at this old revision for how it can be done https://github.com/lulf/watchful/blob/c631bd551dc8057ffdc7984e5efbb1d26e49a446/firmware/app/src/main.rs
